### ISSUE TITLE
node request handler shouldn't normalize headers

### ISSUE THREAD

**Issue by jason0x43** [dojo/dojo2#17]
For better or worse, various servers, particularly WebDriver servers (ghostdriver, QtWebDriver), assume headers will use the common title-case capitalization (e.g., 'Content-Type'). Normalizing the headers causes difficult-to-diagnose issues, and since there isn't any way to indicate to a user that an app is breaking due to a server's assumptions about header case, it doesn't seem to serve a useful purpose.

**Comment by kitsonk** [comment]
I suspect normalising headers is "surprising".  I agree it should be changed.  I have had bad HTTP Servers before make silly assumptions about the casing of headers, and there is little value in normalising them.  Would rather have some custom header break a request than the lib break the request.

**Comment by jason0x43** [comment]
Fixed in 20a03661c53ec3082db49d081050dd48d7f09cdc
