### ISSUE TITLE
xhr should use responseText in IE9

### ISSUE THREAD

**Issue by jason0x43** [dojo/dojo2#19]
`xhr` returns `responseXML` or `response` for the response body, but `response` doesn't exist in IE9 (IE9 uses `responseText`).

**Comment by kitsonk** [comment]
This is addressed in [core](https://github.com/dojo/core/blob/05e7535461162993795aac8491750835b9056867/src/request/xhr.ts#L96), just not present here.

I guess the question is when can we move Intern over to `dojo/core` in order to not to have to patch here.

**Comment by jason0x43** [comment]
We could, although it's a bit kludgey right now since core (and the other dojo2 libs) put their default exports on a `default` property (e.g., when you require `core/request` you don't end up with the `request` function, you get an object that contains `request` as its `default` property).

**Comment by jason0x43** [comment]
Fixed in https://github.com/dojo/dojo2/commit/20a03661c53ec3082db49d081050dd48d7f09cdc
