### ISSUE TITLE
Will Dojo2 be completely programmatic ?

### ISSUE THREAD

**Issue by RobertoMalatesta** [dojo/dojo2#23]
@kitsonk one straight question:

will #dojo2 be completely programmatic?

I mean up to manipulating the single CSS attribute with a dot notation, without having to recur to CSS/HTML/BARFML and forget text based markup completely?

Thank you in advance.

--R

**Comment by kitsonk** [comment]
Issue moved to [dojo/meta #65](https://github.com/dojo/meta/issues/65) via [**ZenHub**](https://www.zenhub.com/)
