### ISSUE TITLE
About Dojo

### ISSUE THREAD

**Issue by jt4000** [dojo/dojo2#25]
Hello,

Im newbie in dojo2 and I got some questions.

1.
What is the benefit to use dojo compare to jquery, bootstrap and anguarJS?

2.
What website have used dojo?

3.
What context is it relevant to use dojo in technical and business perspective?

Thank you!

**Comment by kitsonk** [comment]
As mentioned in the description for this repo, this a pre-pre-pre release version of Dojo 2 that is deprecated.  Please visit [dojo.io](https://dojo.io) or [dojo/meta](https://github.com/dojo/meta) for more information on Dojo 2.
