### ISSUE TITLE
ObserveableArray

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2#6]
The unit tests are failing on this, primarily, because no matter what you do, an "inherited" array will usually never be recognised as an Array.

One way to resolve the test failures is to simply "slice" the ObservableArray so it is an Array for comparison, but also looking at it, I am not sure all the full edge cases are actually called out.  Getting "length" to properly work in an Array descendent is pretty tricky. (here is something that gets most of the edge cases https://github.com/kitsonk/core/blob/master/observe/ObservableArray.js#L89)

So what I am getting at is that the implementation doesn't quite look complete and I don't know if the desire is to just fix the tests for now by "slicing" the array, or to do a more complete implementation of ObservableArray (and one that does offloading to a native implementation if present).

**Comment by kitsonk** [comment]
Anyways, just because it is there at the moment, I have updated the unit tests so they don't fail any more in PR #5.

**Comment by csnover** [comment]
I’ve removed ObservableArray for now.
