### ISSUE TITLE
Promise.all should reject when one of its promises is rejected

### ISSUE THREAD

**Issue by jason0x43** [dojo/dojo2#9]
Currently, `Promise.all` will always resolve, which isn't correct behavior.

A very lightly-tested fix is at https://github.com/jason0x43/dojo2/commit/91df79b47e57f6eee94f10858e65ee9e4d3c62cb.

**Comment by csnover** [comment]
https://github.com/dojo/dojo2/commit/74247e1c96a166156eb09fb8a1958e8304681e11
